config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :home
  resources :notifications
  resources :users
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
    post :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :notification
  acts_as_votable

  validates_presence_of :description, message: 'can not be blank'
  validate :post_id_exists, on: :create

  after_create :comment_counter_inc
  after_destroy :comment_counter_dec

  def comment_counter_inc
    obj = self.post
    obj.no_of_comments = obj.no_of_comments + 1
    obj.save
  end

  def comment_counter_dec
    obj = self.post
    obj.no_of_comments = obj.no_of_comments - 1
    obj.save
  end
  
  def post_id_exists
    return false if Post.find_by_id(self.post_id).nil?
  end

end

app/models/notification.rb
class Notification < ApplicationRecord
  has_many :comments
  after_create_commit { NotificationBroadcastJob.perform_later self}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image
  acts_as_votable

  validates :name, presence: true
  validates :description, presence: true
  validate :user_id_exists, on: :create

  scope :publicpost, -> { where(post_type: 'public') }

  def user_id_exists
    return false if User.find_by_id(self.user_id).nil?
  end

  def public?
    self.post_type == 'public'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_one_attached :avatar
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :age, numericality: { only_integer: true }
  validates :gender, inclusion: { in: %w(M F m f Male Female male female), message: "Not a Valid Gender" }
  validates :user_name, format: { with: /\A^[A-Z][A-Za-z]*\z/ , message: "First CAPITAL letter" }

end

app/models/user_notification.rb
class UserNotification < ApplicationRecord
  belongs_to :comment_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :find_comments
  include Pagy::Backend

  protected

  def find_comments
    @comments = Comment.all.reverse
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :age, :gender, :user_name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :age, :gender, :user_name, :email, :password, :current_password)}
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:edit, :show, :update, :destroy, :upvote, :downvote]
  before_action :find_post, only: [:new, :create, :edit, :update, :upvote, :downvote]
  after_action :user_notification_generate, only: [:create]

  def new
    @comment = Comment.new
  end

  def create
    if current_user
      @comment = current_user.comments.new(comment_params)
      @comment.save
    else
      flash[:notice] = "You must login to Comment..!! "
      redirect_to new_user_session_path
    end
  end

  def edit; end

  def show;  end

  def update
    flash[:notice] =
      if @comment.update(comment_params)
        "Comment Updated"
      else
        "Comment Not Updated"
      end
    redirect_to post_path(@comment.post_id)
  end

  def destroy
    if @comment.destroy
      flash[:notice] = "Comment Destroyed"
      redirect_to post_path(@comment.post_id)
    else
      flash[:notice] = "Comment Not Destroyed"
      redirect_to post_path(@comment.post_id)
    end
  end

  def upvote
    @comment.upvote_by current_user
    redirect_to post_path(@post)
  end  

  def downvote
    @comment.downvote_by current_user
    redirect_to post_path(@post)
  end

  private

  def find_post
    @post = Post.find_by_id(params[:post_id])
  end

  def find_comment
    @comment = Comment.find_by_id(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:post_id, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :find_post, only: [:index]

  def index
    @pagy, @posts = pagy(Post.publicpost, items: 5)
  end

  private

  def find_post
    @post = Post.publicpost.where(id: params[:post_id])
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  
  def index
    @notifications = Notification.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :show, :update, :destroy, :upvote, :downvote]
  before_action :find_comment, only: [:show]

  def index
    @pagy, @posts = pagy(current_user.posts, items: 5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Post created"
      redirect_to @post
    else
      flash[:notice] = "Post Not created"
      render :new
    end
  end

  def show
    flash[:notice] = "Post created"
    @comments = @post.comments
    @comment = Comment.new
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post Updated"
      redirect_to @post
    else
      flash[:danger] = "Post Not Updated"
      redirect_to @post
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = "Post destroyed"
      redirect_to posts_path
    else
      flash[:danger] = "Post Not Destroyed"
      redirect_to posts_path
    end
  end

  def upvote 
    @post.upvote_by current_user
    redirect_to post_path
  end  

  def downvote
    @post.downvote_by current_user
    redirect_to post_path
  end

  private

  def post_params
    params.require(:post).permit(:name, :description, :image, :post_type)
  end

  def find_post
    @post = Post.find_by_id(params[:id])
  end

  def find_comment
    @comment = Comment.find_by_id(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comments_display.html.erb
<div class="comment_show">
Comment: <%= comment.description %><br>
<%= link_to 'Edit', edit_post_comment_path(@post, comment)%>
<%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure ?' } %>
</div><br>

app/views/comments/_errors_display.html.erb
<% if comment.errors.any? %>
  <% comment.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment], remote: (action_name == 'create')) do |form| %>

  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :post_id, :value => @post.id %>
  <div class="field">
    <%= form.label :'Add New Comment :' %>
    <%= form.text_area :description %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div><br>
<% end %>

app/views/comments/create.js.erb
<% if @comment.save %>
  $('#newcomment').append("<%= j render(:partial => 'comments_display', locals: {comment:  @comment}) %>");
<% else %>
	$('#error').text("<%= j render(:partial => 'errors_display', locals: {comment:  @comment}) %>");
<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment : </h1>

<%= render 'form', post_id: @post, comment: @comment %>
<%= link_to 'back', post_path(@comment.post_id) %>

app/views/comments/new.html.erb
<h1>Create New Comment </h1>

app/views/comments/upvote.js.erb
$('#comment_likes').append("<%= j render('post', locals: {post: @post, comment:  @comment}) %>");

app/views/home/index.html.erb
<h1> All Posts</h1>

<table>
  <% @posts.each_slice(5) do |posts| %>
    <tr>
      <div class="row">
        <% posts.each do |post| %>
          <td>
            <div class="<%= post.public? ? 'public' : 'private' %>">
              <%= render 'posts/post_display', post: post %>
              <%= link_to 'Show', post_path(post) %>
            </div><br>
          </td>
        <% end %>
      </div>
    </tr>
  <% end %>
</table>
<%== pagy_nav(@pagy) %> </p>

app/views/layouts/_pagy_boot_nav.html.erb
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Previous</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background">
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/home#index">Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <%#= link_to 'Globat Chat', notifications_path, method: :get, class: "nav-link inactive"%>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <% if current_user %>
              <li class="nav-item">
                <%= link_to "My Posts", posts_path, class: "nav-link active" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "My posts", posts_path, class: "nav-link disabled" %>
              </li>
            <% end %>
          </ul>

          <form class="form-inline mt-md-0">
            <% if current_user %>
              <div class="btn-group">
                <button type="button" class="btn btn-info dropdown-toggle"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> N
                </button>
                <div class="dropdown-menu", style="width: 300px">
                  <% @comments.each do |comment| %>
                    <% if comment.post_id == current_user.posts.ids %>
                      <%= link_to comment.description, post_path(comment.post_id) %> created by "<%= User.find(id = comment.user_id).user_name %>" for "<%=  Post.find(id = comment.post_id).name %>" post
                      <div class="dropdown-divider"></div>
                    <% end %>
                  <% end %>
                </div>
              </div>

              <a class="nav-link" style="color: #ff0000"><%= current_user.email %></a>
              <%= link_to 'Signout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success my-2 my-sm-0' %>
              <% if current_user.avatar.attached? %>
                <a class="navbar-brand" href="/devise/registrations#edit">
                  <%= image_tag current_user.avatar, class: 'img-responsive', id: "user_avatar" %>
                </a>
              <% else %>
                <a class="navbar-brand" href="/devise/registrations#edit">
                  <%= image_tag ("/assets/us.png"), class: 'img-responsive', id: "user_avatar", :size => "45x45" %>
                </a>
              <% end %>
            <% else %>
              <%= link_to 'Signin', new_user_session_path, class: 'btn btn-outline-success my-2 my-sm-0' %>
            <% end %>
          </form>
        </div>
      </nav>
    </header>
    
    <% flash.each do |type, message| %>
      <%
        next unless message
        level = case type
          when 'notice' then 'success'
          when 'alert'  then 'error'
          when 'info'   then 'info'
          when 'warn'   then 'warn'
        end
      %>
      <script>iziToast.show({position: 'center', message: '<%=j message.html_safe %>'});</script>
    <% end %>

    <div class="container pt-3">
      <div class="row justify-content-sm-left" >
        <div class="col-md-<%= yield(:container_width).presence || '4' %>">
          <%= yield %>
        </div>
      </div>
    </div>

    <footer class="footer fixed-bottom">
      <div class='container'>
        <span class="text-muted">Project 2019, All Right Reserved</span>
      </div>
    </footer>

  </body>
</html>

app/views/notifications/_notification.html.erb
<div class="notification">
  <p><%= notification.id %>. <%= notification.content %></p>
</div>

app/views/notifications/index.html.erb
<h1>Global Chat Room</h1>

<form>
  <label>Enter Text</label><br>
  <input type="text" data-behavior="chat_speaker">
</form>

<div id="notifications">
  <%= render @notifications.reverse %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, remote: true) do |form| %>
  
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div><br>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div><br>

  <div class="field">
    <%= form.label :post_type %>
    <%= form.radio_button :post_type, 'public', :checked => true %>
    <%= label :post_type, 'public' %>
    <%= form.radio_button :post_type, 'private' %>
    <%= label :post_type, 'private' %>
  </div><br>

  <div class="btn btn-outline-info">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div><br>
<% end %>

app/views/posts/_post_display.html.erb
<% if post.image.attached? %>
  <%= image_tag post.image, style:"width:150px; height:100px" %><br>
<% else %>
  <%= image_tag ("/assets/na.jpg"), style:"width:150px; height:100px" %><br>
<% end %>

Post Name: <%= post.name %><br>
Post Description: <%= post.description %><br>
Post Comments: <%= post.no_of_comments %><br>

app/views/posts/edit.html.erb
<h2> Edit Post </h2>

<%= render 'form', post: @post %>
<%= link_to 'back', posts_path %>

app/views/posts/index.html.erb
<h1>Your Posts...</h1>

<%= link_to 'Create new Post', new_post_path %><br></br>

<table>
  <% @posts.each_slice(5) do |posts| %>
    <tr>
      <% posts.each do |post| %>
        <td>
          <div class="<%= post.public? ? 'public' : 'private' %>">
            <%= render 'post_display', post: post %>
            <%= link_to 'Show', post_path(post) %>
            <%= link_to 'Edit', edit_post_path(post) %>
            <%= link_to 'Delete', post_path(post), method: :delete,
                data: { confirm: 'Are you sure want to delete?' } %>
          </div><br>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<%== pagy_nav(@pagy) %>

app/views/posts/new.html.erb
<h1> Create New Post </h1>
 
<%= render 'form', post: @post %>
<%= link_to 'back', posts_path %>

app/views/posts/show.html.erb
<div class="post_show">
  <%= render 'post_display', post: @post %><br></br>
  <% if current_user %>
    <% if @post.user_id == current_user.id %>
      <%= link_to 'Edit', edit_post_path(@post) %>
      <%= link_to 'Delete', post_path(@post), method: :delete,
      data: {confirm: 'Are you sure want to delete?'} %><br>
    <% end %>
  <% end %>

  <%= link_to image_tag("/assets/like.png", :size => "100x40"), like_post_path(@post), method: :put, remote: true %>
  <%= @post.get_upvotes.size %><br>
  <%= link_to image_tag("/assets/dislike.png", :size => "100x40"), dislike_post_path(@post), method: :put, remote: true %>
  <%= @post.get_downvotes.size %><br>
</div>

<% if @comment.present? %>
  <h2>Comments of This Post ...</h2>
  <% @comments.each do |comment| %>
    <div class="comment_show">
      Comment: <%= comment.description %><br>

      <%= link_to image_tag("/assets/like2.png", :size => "30x30"), like_post_comment_path(@post, comment), method: :put, remote: true %>
      <%= comment.get_upvotes.size %>
      <%= link_to image_tag("/assets/dislike2.png", :size => "40x40"), dislike_post_comment_path(@post, comment), method: :put, remote: true %>
      <%= comment.get_downvotes.size %><br>
      <% if current_user %>
        <% if comment.user_id == current_user.id %>
          <%= link_to 'Edit', edit_post_comment_path(@post, comment)%>
          <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure ?' } %>
        <% end %>
      <% end %>
    </div><br>
  <% end %>
<% end %>  

<div id="newcomment"></div>
<div id="error"></div>

<%= render 'comments/form',  post_id: @post, comment: @comment %>
<%= link_to 'Back', root_path %><br></br>

app/views/user/index.html.erb
<h1> Welcome </h1>